export const SIGN_IN = "SIGN_IN";
export const CREATE_USER = "CREATE_USER";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const IS_AUTH_LOADING = "IS_AUTH_LOADING";

export const CREATE_POST = "CREATE_POST";
export const FETCH_ALL_POSTS = "FETCH_ALL_POSTS";
export const FETCH_ALL_POSTS_BY_USER_ID = "FETCH_ALL_POSTS_BY_USER_ID";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";
export const IS_POSTS_LOADING = "IS_POSTS_LOADING";
export const IS_POST_CREATE_LOADING = "IS_POST_CREATE_LOADING";
export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";
export const REGISTER_LOADING = "REGISTER_LOADING";
export const FETCH_POSTS_ERROR = "FETCH_POSTS_ERROR";
export const FETCH_RECOMMENDED_POSTS = "FETCH_RECOMMENDED_POSTS";
export const FETCH_TRENDING_POSTS = "FETCH_TRENDING_POSTS";

export const IS_COMMENT_CREATE_LOADING = "IS_COMMENT_CREATE_LOADING";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const CREATE_COMMENT_ERROR = "CREATE_COMMENT_ERROR";
export const IS_FETCH_COMMENTS_LOADING = "IS_FETCH_COMMENTS_LOADING";
export const FETCH_COMMENTS_ERROR = "FETCH_COMMENTS_ERROR";

export const POST_LIKED = "POST_LIKED";
export const POST_UNLIKED = "POST_UNLIKED";
export const LIKE_POST_ERROR = "LIKE_POST_ERROR";
export const UNLIKE_POST_ERROR = "UNLIKE_POST_ERROR";
export const FETCH_LIKED_POSTS_BY_USER_ID = "FETCH_LIKED_POSTS_BY_USER_ID";
export const FETCH_LIKED_POST_ERROR = "FETCH_LIKED_POST_ERROR";
